name = "pac-web01-slides"
account_id = "f0bc7ec7044f8adcb49847171a523318"
main = "src/index.ts"
compatibility_date = "2026-09-25"

routes = [
  { pattern = "w.othiagomagalhaes.com/pac-web01-slides*", zone_id = "dbe0114fc9bc769f514ad674b143c02b" },
  { pattern = "w.othiagomagalhaes.com/api/*", zone_id = "dbe0114fc9bc769f514ad674b143c02b" },
]

[assets]
directory = "../dist/pac-web01-slides"
binding = "ASSETS"
not_found_handling = "single-page-application"

[[d1_databases]]
binding = "DB"
database_name = "pac-web01-slides"
database_id = "ea145beb-610f-4f61-a60f-17ca8e564c7f"
migrations_dir = "migrations"

[vars]
SESSION_DAYS = "90"
PRESENTER_AUTH_REQUIRED = "true"
